### ISSUE TITLE
Incompatible with Angular > 1.2.16

### ISSUE THREAD

**Issue by petergillardmoss** [Yankovsky/nouislider-angular#1]
Hello,

Angular is at v1.3.1 but I can't upgrade because angular-nouislider reports as incompatible.

Is it possible to update the package please?

Thanks
Peter

**Comment by Yankovsky** [comment]
@petergillardmoss Hello! I've updated nouislider-angular plugin so it now uses angular ~1.4.7 and nouislider ~8.0.2.
