### ISSUE TITLE
tooltip option error

### ISSUE THREAD

**Issue by bmutari** [Yankovsky/nouislider-angular#10]
setting slider tooltip option to true creates "TypeError: Cannot assign to read only property '0' of 78

also are pips/scales supported?

**Comment by Yankovsky** [comment]
@bmutari I'll check tooltip option today. Pips are working, as you can see in [demo example](http://yankovsky.github.io/nouislider-angular/examples/#/options)

**Comment by Yankovsky** [comment]
@bmutari I just checked, tooltips option works nicely. I added [an example](http://localhost:61967/noUiSlider-angularjs/examples/index.html#/tooltips) with simple `tooltips: true` option.
However, if you are using latest nouislider there can be some problems, because events system was reworked a bit. This angular wrapper use 8.1.0 version of nouislider and the latest is 8.2.1. I will update plugin, but later, maybe on next week.

**Comment by johnprice99** [comment]
Hi, thank you for this directive. Are there any plans to update this any time soon? We need to use the latest version of noUISlider for the updated tooltip, but would also like to continue using this.

Thanks

**Comment by johnprice99** [comment]
I have managed to fix the problem I was having: it was a problem with this line https://github.com/Yankovsky/nouislider-angular/blob/master/nouislider.js#L86 where newValue always comes back as an array (if a single handle, then it is an array of one value). I'm happy to make a PR, if you would like?

**Comment by Yankovsky** [comment]
@johnprice99 Hi! I am very happy to hear that this plugin is useful to you.
As for issue, I've just checked [the first example from demo](http://yankovsky.github.io/nouislider-angular/examples/#/). As you see noUiSlider 8.1.0 returns a number (not array) when there is only one handle. At least it worked this way.
![](http://i.imgur.com/sPnbrdE.png)
Unfortunately, I have no time to investigate this issue. I'll try in the weekend.
PRs are welcome! Don't forget to check/update demo and docs.

**Comment by johnprice99** [comment]
@Yankovsky yeah good point - this plugin should be backwards compatible too :smile: 

If I get time I am happy to try a fix for both versions, but for now I will just fork this repo. Thanks

**Comment by Yankovsky** [comment]
@johnprice99 it is ok to create new version for new version of noUiSlider plugin. Just check if all other examples are working properly after your fix.

**Comment by Yankovsky** [comment]
@johnprice99 @bmutari I know that it was quite a while, but could you check latest version (2.5.4) of nouislider-angular? All your issues should be fixed by now.

**Comment by Yankovsky** [comment]
@johnprice99 @bmutari please confirm that the bug is fixed, so I will close the issue
