### ISSUE TITLE
Bower version mismatch

### ISSUE THREAD

**Issue by Ziao** [Yankovsky/nouislider-angular#13]
Hey,

Your latest tag, 2.4.1 still includes a bower file that says 2.3.0, which bower refuses to install.

Thanks :)

**Comment by Ziao** [comment]
As far as I know, you can safely remove the version property completely from bower.json

**Comment by Yankovsky** [comment]
@Ziao hi! Current version is 2.5.4 and it is the same in package.json and bower.json. I'll try to remove version from bower.json in next release. Thank you!
