### ISSUE TITLE
Add separate binding for value

### ISSUE THREAD

**Issue by Misiu** [Yankovsky/nouislider-angular#14]
I'm trying to build editor for array on numbers using Your directive (as I described in here: http://stackoverflow.com/questions/36306783/nouislider-in-angular-bind-to-array-of-numbers)

My main problem is ability to bind same options objects to multiple instances, but in same time have separated value for each instance - binded to element of array.

[This is the expected result ](http://plnkr.co/edit/4VgDnm?p=preview)using current version of directive. As You can see in **scripts.js** I must create options for each instance and update my array using events.

[This is second version](http://plnkr.co/edit/WnxhZLGvssMBKYg6SgUf?p=preview) using modified directive (noui.angular.js file), as You can see **scripts.js** file is much easier. What I've added is binding called **yaNoUiSliderValue** and at start I check if start is set in options, if not I'm using value from my binding.

I'm not an expert so maybe You could take a look at this and maybe You would consider adding this extra binding. It would be helpful when creating editors as I described.

**Comment by Yankovsky** [comment]
@Misiu hi! I know, that it has been a while, but I added an example solution to your issue http://yankovsky.github.io/nouislider-angular/examples/#/multiple-sliders-binding
Let me know if it suits your needs.
