### ISSUE TITLE
How to set the value of the slider dynamically?

### ISSUE THREAD

**Issue by jackroscoe** [Yankovsky/nouislider-angular#21]
The documentation for nouislider specifies a [set() method](http://refreshless.com/nouislider/slider-read-write/#section-setting) that can be used to set the current value of the slider.

I can see in your documentation you reference `$scope.eventHandlers` which allows us to listen for the set method, but not trigger it.

Is there a way to do this?

Thanks for any help!

**Comment by Yankovsky** [comment]
It is angular wrapper we are talking about, so value could be changed using two way binding. Check examples at http://yankovsky.github.io/nouislider-angular/examples/#/
By changing value of options.start you can dynamically change value on slider.
Describe your use case, please.

**Comment by jackroscoe** [comment]
Ah, of course. Thank you!
