### ISSUE TITLE
How to use noUiSlider in a directive

### ISSUE THREAD

**Issue by JoostvdB94** [Yankovsky/nouislider-angular#25]
First of all: Great job developing this directive

I wanted to implement the slider into a custom directive, but it seems that the eventhandlers are not found. 

This piece of code is taken from the link method. The options are set in a similar way and they do work.

```
this.eventHandlers = {
            update: (values, handle, unencoded) => {
                console.log('Update!' + values);
            },
            set: (values, handle, unencoded) => {
                 console.log('set!' + values);
            }
        };
        $scope.directive = this;
```

The corresponding HTML code:

```
<div class="col-md-9">
    <div ya-no-ui-slider="directive.options" 
         ya-no-ui-slider-events="directive.eventHandlers" 
         id="{{directive.sliderId}}" 
         style="color:black;margin-bottom:35px;">
    </div>
</div>
```

But none of the events are getting fired. The piece of code:
`noUiSliderEvents = $scope.$parent.$eval($attrs.yaNoUiSliderEvents),` 
results in being undefined.

Could you help me?

Thanks in advance!

**Comment by JoostvdB94** [comment]
Fixed it myself!
Be sure to use the `controller` function instead of the `link` method. `link` gets called too late!

**Comment by Yankovsky** [comment]
@JoostvdB94 👍 well done
