### ISSUE TITLE
remark/question on directive

### ISSUE THREAD

**Issue by flythird** [Yankovsky/nouislider-angular#28]
Hello ! 

very useful, thanks to you. 

I use both, your angular work and the native api, i use it in a collection loop and i remark :

i am not able to bind each of my sliders with another object or a ng-model input.
i need to use tricks and events to succeed the binding.

an event does'nt give access to the slider instance object  (same remark with 'options')
is there any easy or faster way to access to the instance.

thank you, from cheese land, in the south.... of course (or france)
alien

**Comment by Yankovsky** [comment]
@flythird Hi! Can you show me an example of your issue?

**Comment by flythird** [comment]
it is not an issue look with angular: 

div ng-repeat=item in items
 imput type=text ......   

 div ya-no-ui-slider="$ctrl.sliderOptions" ya-no-ui-slider-events="$ctrl.evh()"  /div
 
 /div
 

Each slider does'nt  give me the possibility to interact with each input. There is no link in evh event able to give me the access to the input. I need to update a knob with a ng-model for each item.

thanks

**Comment by Yankovsky** [comment]
@flythird there is an example of [multiple sliders binding](http://yankovsky.github.io/nouislider-angular/examples/#!/multiple-sliders-binding)
It is better to stick with angular api and not mix it with direct dom manipulation.
Do you still need help with that issue?

**Comment by flythird** [comment]
Hello !

Thank you for your answer but i have stopped to work with angular.
My project is waiting for me but in fact i preferred to change angular
by replacing it with the Vue.js framework. 

I am looking for time and energy to rewrite my project so sorry this
question is closed today.  


thanks for your attention and have a nice day, alan


Le Fri, 17 May 2019 00:33:29 -0700,
Yankovsky Andrey <notifications@github.com> a écrit,


> @flythird there is an example of [multiple sliders
> binding](http://yankovsky.github.io/nouislider-angular/examples/#!/multiple-sliders-binding)
> It is better to stick with angular api and not mix it with direct dom
> manipulation. Do you still need help with that issue?
> 


---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
