### ISSUE TITLE
It brokes array

### ISSUE THREAD

**Issue by Kopleman** [Yankovsky/nouislider-angular#6]
Current version is broken, $scope.values = [60, 90]; after triggering directive leads to $scope.values =  60; problem coused by this code: 

`value = element.noUiSlider.get();
var valueIsArray = angular.isArray(value);
if (valueIsArray) value = value[0];`

i rewrited function and have this one : 
`function () {
value = element.noUiSlider.get();
var valueIsArray = angular.isArray(value);
 if (valueIsArray) {
      value = [parseFloat(value[0]) || scope.noUiSlider.range.min, parseFloat(value[1]) ||        scope.noUiSlider.range.max];
                                value = [
                                        Math.min(Math.max(value[0], scope.noUiSlider.range.min), scope.noUiSlider.range.max),
                                        Math.min(Math.max(value[1], scope.noUiSlider.range.min), scope.noUiSlider.range.max)
                                ];
                            } else {
                                value = parseFloat(value) || 0;
                                value = Math.min(Math.max(value, scope.noUiSlider.range.min), scope.noUiSlider.range.max);
                            }  
                            newValue = value;
                            ngModel.$setViewValue(newValue);
                        });`

works fine atm with arrays and single values

**Comment by Yankovsky** [comment]
@Kopleman Hello! Please check new version of plugin, it shouldn't have this problem.

**Comment by Yankovsky** [comment]
Thank you for your contribution!
