### ISSUE TITLE
No array syntax for dependency injection

### ISSUE THREAD

**Issue by dilshanraja** [Yankovsky/nouislider-angular#9]
The non-minified version isn't adhering to angular standards of dependency injection using array syntax. Requires the explicit inclusion of the minified version with the rails asset pipeline to avoid errors in production.

**Comment by Yankovsky** [comment]
@dilshanraja Ok, this one is easy to solve :)

**Comment by Yankovsky** [comment]
@dilshanraja fixed in version v2.2.1
